<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventListener\ExceptionSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventListener/ExceptionSubscriber.php';

return $this->privates['App\\EventListener\\ExceptionSubscriber'] = new \App\EventListener\ExceptionSubscriber(($this->services['twig'] ?? $this->getTwigService()), $this);
