<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container219Y7Bb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container219Y7Bb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container219Y7Bb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container219Y7Bb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container219Y7Bb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '219Y7Bb',
    'container.build_id' => 'db3c6833',
    'container.build_time' => 1593440184,
], __DIR__.\DIRECTORY_SEPARATOR.'Container219Y7Bb');
