<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTmKS2eo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTmKS2eo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTmKS2eo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTmKS2eo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTmKS2eo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TmKS2eo',
    'container.build_id' => '620e0d0c',
    'container.build_time' => 1587330874,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTmKS2eo');
